### ISSUE TITLE
Cant deploy

### ISSUE THREAD

**Issue by olszak94** [pandaac/pandaac#7]
So before i had problem in this issue #5 now it's kind of similar, instead of not working sub-pages, whole website is blank, it doesn't even load. I have no idea why.

**Comment by eklundchristopher** [comment]
What webserver are you using?

If Apache, make sure `AllowOverride` is set to `All`. Otherwise, the rewrites in the .htaccess file won't work.

If Nginx, please share your virtual host file.

_PS. Unfortunately, just as last time, we're still missing some features (e.g. guilds are a work in progress, forums are non-existent), we're not quite ready for a stable production level. If this is fine by you, by all means, go ahead and use it, but expect there to be bugs and missing features._

**Comment by olszak94** [comment]
Sorry for late reply, this is my nginx virtual host file.

```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/html;
    index index.php index.html index.htm;

    server_name myservername.info;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /var/www/html;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    client_max_body_size 20m;

    location ~ /ajenti.* {
        rewrite (/ajenti)$ / break;
        rewrite /ajenti/(.*) /$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect / /ajenti/;
        proxy_set_header Host $host;
        proxy_set_header Origin http://$host; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }
}
```

**Comment by eklundchristopher** [comment]
You need to add the public/ directory onto the root directive, i.e. `root /var/www/html/public;`
